version: '3'
services:
  php:
    image: php:8.1-fpm
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test_db_user
      MYSQL_PASSWORD: test_db_user_pass
      MYSQL_DATABASE: test_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
      
      